activeEnv: testEnv
browser:
  browserName: chrome
  browserAttachScreenshot: false
  headlessMode: false
  browserTimeout: 6
  timeout: 10
environments:
  testEnv:
    envName: testEnv
    appUrl: http://146.59.32.4/index.php
    title: Filmweb - filmy takie jak Ty!
    menSubCategoryText: MEN
    stationerySubCategoryText: STATIONERY
    artCategoryText: ART
  intEnv:
    envName: intEnv
    appUrl: https://www.selenium.dev/
    title: Selenium